apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-connections-backend
  title: '@backstage/connections-backend'
  description: Backend service implementation for the Backstage connections framework
spec:
  lifecycle: experimental
  type: backstage-node-library
  owner: framework-maintainers
